{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "postgresql.v1.primary.fullname" . }}
  labels:
    app: {{ include "common.names.name" . }}
    chart: {{ include "common.names.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "postgresql.v1.primary.fullname" . }}
                port:
                  number: {{ include "postgresql.v1.service.port" . }}
{{- end }}
